version: "2"
services:
  fontend:
    container_name: "react-unity-app"
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/src
      - /app/node_modules